# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec66b4fe0fe860a7b62b208166983dafcbd5473a7c38e6a517b56fecb559b69ee839f743fe6f44efd18ec0c6e17647d376cc388d65dc4893840e4e9337dd4518

test:
  secret_key_base: b176b94e954d7cf6f27613594d253e52bed0e51049cff04747caecfafd1656b13bf033adb99f01652cf22a128192c630564b527e00a3268e6ec30a2d8666ffcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
